// Building catalog.
//
// A building type declares what it costs, how much work it takes to raise,
// how many people can work in it and what that work does. Everything else
// (the build planner, the job scheduler, the sprite generator and the build
// panel) is driven from these fields, so a new type only has to be added here.
//
// Sizes are in grid cells; wall and roof heights are in cell widths, so a
// building keeps its proportions when the cell size of the world changes.

export const CATEGORIES = {
  home: 'Homes',
  store: 'Storage',
  gather: 'Gathering',
  craft: 'Workshops',
  civic: 'Civic',
};

export const BUILDINGS = [
  {
    id: 'hut',
    label: 'Hut',
    category: 'home',
    w: 1,
    h: 1,
    wallH: 0.6,
    roofH: 0.35,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-trunk' },
    cost: { wood: 8, fiber: 5 },
    work: 18,
    housing: 3,
    comfort: 0.4,
    base: true,
    note: 'Poles and thatch. The first shelter anyone builds.',
  },
  {
    id: 'house',
    label: 'House',
    category: 'home',
    w: 2,
    h: 1,
    wallH: 0.9,
    roofH: 0.45,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-stone' },
    cost: { plank: 10, stone: 6 },
    work: 45,
    housing: 5,
    comfort: 0.75,
    note: 'A framed house on a stone footing.',
  },
  {
    id: 'manor',
    label: 'Manor',
    category: 'home',
    w: 2,
    h: 2,
    wallH: 1.26,
    roofH: 0.55,
    palette: { wall: 'mat-brick', roof: 'mat-thatch', trim: 'mat-stone' },
    cost: { brick: 18, plank: 14, cloth: 4 },
    work: 120,
    housing: 10,
    comfort: 1,
    note: 'Brick walls, glazed windows, room for a large household.',
  },
  {
    id: 'storehouse',
    label: 'Storehouse',
    category: 'store',
    w: 2,
    h: 1,
    wallH: 0.78,
    roofH: 0.4,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-trunk' },
    cost: { wood: 14 },
    work: 30,
    storage: 500,
    isStore: true,
    base: true,
    note: 'Where everything gathered is dropped off and drawn from.',
  },
  {
    id: 'granary',
    label: 'Granary',
    category: 'store',
    w: 2,
    h: 1,
    wallH: 0.96,
    roofH: 0.5,
    palette: { wall: 'mat-plank', roof: 'mat-thatch', trim: 'mat-brick' },
    cost: { plank: 10, brick: 6 },
    work: 55,
    storage: 400,
    isStore: true,
    keepsFood: 0.7,
    note: 'Raised and dry: food keeps far longer here.',
  },
  {
    id: 'woodcutter',
    label: 'Woodcutter camp',
    category: 'gather',
    w: 1,
    h: 1,
    wallH: 0.54,
    roofH: 0.3,
    palette: { wall: 'mat-trunk', roof: 'mat-thatch', trim: 'mat-timber' },
    cost: { wood: 6 },
    work: 14,
    slots: 2,
    radius: 16,
    job: { type: 'harvest', classes: ['tree', 'shrub'], yields: { wood: 1, fiber: 0.15 } },
    base: true,
    note: 'Fells grown trees and shrubs for timber. The forest regrows.',
  },
  {
    id: 'forager',
    label: 'Forager hut',
    category: 'gather',
    w: 1,
    h: 1,
    wallH: 0.48,
    roofH: 0.3,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-stem' },
    cost: { wood: 4, fiber: 4 },
    work: 12,
    slots: 2,
    radius: 18,
    job: {
      type: 'harvest',
      classes: ['ground', 'herb', 'vine'],
      yields: { food: 1, fiber: 0.4 },
      // Ground cover is cut back rather than pulled up, so a patch that is
      // picked keeps growing back. This is what makes foraging renewable and
      // ties the food supply to the growth rates set in the species panel.
      regrow: 0.35,
    },
    base: true,
    note: 'Picks the low growth for food and fiber; mats are cut back, not pulled up.',
  },
  {
    id: 'quarry',
    label: 'Quarry',
    category: 'gather',
    w: 2,
    h: 1,
    wallH: 0.36,
    roofH: 0.2,
    palette: { wall: 'mat-stone', roof: 'mat-stone', trim: 'mat-timber' },
    cost: { wood: 10 },
    work: 32,
    slots: 3,
    radius: 14,
    site: 'deposit:stone',
    job: { type: 'mine', deposit: 'stone', yields: { stone: 1 } },
    note: 'Works a stone deposit until it is spent.',
  },
  {
    id: 'claypit',
    label: 'Clay pit',
    category: 'gather',
    w: 1,
    h: 1,
    wallH: 0.3,
    roofH: 0.15,
    palette: { wall: 'mat-soil', roof: 'mat-soil', trim: 'mat-timber' },
    cost: { wood: 8 },
    work: 24,
    slots: 2,
    radius: 14,
    site: 'deposit:clay',
    job: { type: 'mine', deposit: 'clay', yields: { clay: 1 } },
    note: 'Digs the clay banks near water.',
  },
  {
    id: 'mine',
    label: 'Mine',
    category: 'gather',
    w: 2,
    h: 2,
    wallH: 0.72,
    roofH: 0.35,
    palette: { wall: 'mat-timber', roof: 'mat-stone', trim: 'mat-metal' },
    cost: { plank: 12, stone: 10 },
    work: 90,
    slots: 3,
    radius: 16,
    site: 'deposit:ore',
    job: { type: 'mine', deposit: 'ore', yields: { ore: 1 } },
    note: 'Props and a shaft down to the ore.',
  },
  {
    id: 'farm',
    label: 'Farm',
    category: 'gather',
    w: 2,
    h: 2,
    wallH: 0.54,
    roofH: 0.3,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-stem' },
    cost: { wood: 8, fiber: 4 },
    work: 40,
    slots: 3,
    radius: 3,
    site: 'fertile',
    fields: 2,
    job: { type: 'farm', yields: { food: 1 } },
    note: 'Sown fields around the barn; yield follows soil fertility.',
  },
  {
    id: 'sawpit',
    label: 'Sawpit',
    category: 'craft',
    w: 2,
    h: 1,
    wallH: 0.54,
    roofH: 0.25,
    palette: { wall: 'mat-timber', roof: 'mat-thatch', trim: 'mat-trunk' },
    cost: { wood: 10, stone: 4 },
    work: 40,
    slots: 2,
    job: { type: 'craft', in: { wood: 2 }, out: { plank: 1 }, time: 3 },
  },
  {
    id: 'charcoalHearth',
    label: 'Charcoal hearth',
    category: 'craft',
    w: 1,
    h: 1,
    wallH: 0.48,
    roofH: 0.25,
    palette: { wall: 'mat-stone', roof: 'mat-soil', trim: 'mat-trunk' },
    cost: { stone: 8, wood: 4 },
    work: 26,
    slots: 1,
    smoke: 1,
    job: { type: 'craft', in: { wood: 3 }, out: { charcoal: 1 }, time: 4 },
  },
  {
    id: 'kiln',
    label: 'Kiln',
    category: 'craft',
    w: 1,
    h: 1,
    wallH: 0.72,
    roofH: 0.25,
    palette: { wall: 'mat-brick', roof: 'mat-stone', trim: 'mat-soil' },
    cost: { stone: 10, clay: 6 },
    work: 45,
    slots: 2,
    smoke: 1,
    job: { type: 'craft', in: { clay: 2, charcoal: 1 }, out: { brick: 2 }, time: 4 },
  },
  {
    id: 'weaver',
    label: 'Weaver',
    category: 'craft',
    w: 1,
    h: 1,
    wallH: 0.72,
    roofH: 0.35,
    palette: { wall: 'mat-plank', roof: 'mat-cloth', trim: 'mat-timber' },
    cost: { plank: 6, wood: 4 },
    work: 35,
    slots: 2,
    job: { type: 'craft', in: { fiber: 3 }, out: { cloth: 1 }, time: 4 },
  },
  {
    id: 'smelter',
    label: 'Smelter',
    category: 'craft',
    w: 2,
    h: 1,
    wallH: 0.96,
    roofH: 0.25,
    palette: { wall: 'mat-brick', roof: 'mat-stone', trim: 'mat-metal' },
    cost: { brick: 12, stone: 8 },
    work: 80,
    slots: 2,
    smoke: 2,
    job: { type: 'craft', in: { ore: 2, charcoal: 2 }, out: { metal: 1 }, time: 5 },
  },
  {
    id: 'smithy',
    label: 'Smithy',
    category: 'craft',
    w: 2,
    h: 1,
    wallH: 0.84,
    roofH: 0.4,
    palette: { wall: 'mat-brick', roof: 'mat-thatch', trim: 'mat-metal' },
    cost: { brick: 10, plank: 8 },
    work: 85,
    slots: 2,
    smoke: 1,
    job: { type: 'craft', in: { metal: 1, charcoal: 1 }, out: { tool: 1 }, time: 6 },
  },
  {
    id: 'workshop',
    label: 'Workshop',
    category: 'craft',
    w: 2,
    h: 2,
    wallH: 1.08,
    roofH: 0.45,
    palette: { wall: 'mat-brick', roof: 'mat-plank', trim: 'mat-metal' },
    cost: { brick: 14, plank: 12, tool: 2 },
    work: 140,
    slots: 4,
    job: { type: 'craft', in: { metal: 2, plank: 2 }, out: { tool: 3 }, time: 5 },
    note: 'Machines and jigs: three tools for the metal that made one.',
  },
  {
    id: 'school',
    label: 'School',
    category: 'civic',
    w: 2,
    h: 1,
    wallH: 1.02,
    roofH: 0.5,
    palette: { wall: 'mat-plank', roof: 'mat-thatch', trim: 'mat-brick' },
    cost: { plank: 12, brick: 6 },
    work: 70,
    slots: 3,
    job: { type: 'research' },
    note: 'Scholars turn a fed population into research points.',
  },
  {
    id: 'market',
    label: 'Market',
    category: 'civic',
    w: 2,
    h: 2,
    wallH: 0.66,
    roofH: 0.3,
    palette: { wall: 'mat-cloth', roof: 'mat-cloth', trim: 'mat-timber' },
    cost: { plank: 14, cloth: 4 },
    work: 90,
    slots: 2,
    job: { type: 'trade' },
    isMarket: true,
    note: 'Sets prices and lets caravans buy the surplus.',
  },
  {
    id: 'well',
    label: 'Well',
    category: 'civic',
    w: 1,
    h: 1,
    wallH: 0.42,
    roofH: 0.25,
    palette: { wall: 'mat-stone', roof: 'mat-timber', trim: 'mat-metal' },
    cost: { stone: 12 },
    work: 40,
    health: 0.35,
    radius: 12,
    note: 'Clean water: fewer deaths, faster recovery.',
  },
];

export const BUILDING_BY_ID = Object.fromEntries(BUILDINGS.map((b) => [b.id, b]));

export function defaultBuildConfig() {
  return {
    costScale: 1,
    workScale: 1,
    autoBuild: true,
    maxSites: 3,
    spacing: 1,
    // How far a new building may be placed from the center of the settlement.
    sprawl: 22,
    // Planner weights: how badly the settlement wants each category.
    weights: { home: 1, store: 1, gather: 1, craft: 1, civic: 0.8 },
    // Housing headroom kept ahead of the population, in people.
    housingSlack: 3,
    // People per building of a category before a second one is worth raising.
    // Homes are left out: how many are needed follows from the housing need.
    perType: { store: 12, gather: 4, craft: 8, civic: 14 },
  };
}

export function scaledCost(def, cfg) {
  const out = {};
  for (const [id, n] of Object.entries(def.cost || {})) {
    out[id] = Math.max(1, Math.round(n * (cfg.costScale || 1)));
  }
  return out;
}

export function scaledWork(def, cfg) {
  return Math.max(1, (def.work || 10) * (cfg.workScale || 1));
}

export function slotsOf(def) {
  return def.slots || 0;
}

export function isUnlocked(def, unlockedSet) {
  return !!def.base || unlockedSet.has(def.id);
}

export function siteNeed(def) {
  if (!def.site) return null;
  const [kind, arg] = def.site.split(':');
  return { kind, arg };
}
