//! Menu search: turning what somebody types into the place in the menus that
//! does the thing.
//!
//! The index is not written by hand. Every labeled control the panels build
//! carries a `data-find` stamp, and a harvest tool walks the running page,
//! visiting every mode and tab, and writes what it found to
//! `assets/menu-index.json`. That file is baked into the binary here, so the
//! index cannot describe a control the build does not have.
//!
//! Ranking has two halves. Fuzzy matching is the default and is all in this
//! file: it wants the letters somebody typed to be in the label. Meaning
//! matching is optional and needs a table this crate cannot build (see
//! `find_terms`), so it arrives separately and is folded in only when it is
//! both loaded and asked for.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

/// The index harvested from the built page. Regenerated by `menuindex.js`.
pub const INDEX_JSON: &str = include_str!("../../assets/menu-index.json");

/// The meaning table, built by the `menu-terms` tool. Empty until it is run,
/// which is why matching on meaning is something to switch on rather than the
/// way search works.
pub const TERMS_JSON: &str = include_str!("../../assets/menu-terms.json");

/// Below this nothing is worth showing; a match this weak is noise.
pub const FLOOR: f64 = 0.24;

/// How many rows a search hands back when nobody says otherwise.
pub const DEFAULT_LIMIT: usize = 12;

/// What being on the screen already is worth. Small on purpose: it settles
/// which of two equally good matches comes first, and it does not let a hint
/// match on this tab climb over a label match on another one.
const NEAR_MODE: f64 = 0.06;
const NEAR_TAB: f64 = 0.04;

/// One place somebody can be sent: a control in a panel, a tab, or a fixed
/// button in the chrome that is there whatever mode is showing.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct Entry {
    /// `lab`, `sprites`, `settlement`, or empty for something on every screen.
    #[serde(default)]
    pub mode: String,
    #[serde(default)]
    pub mode_label: String,
    /// The tab id this lives under, empty for chrome.
    #[serde(default)]
    pub tab: String,
    #[serde(default)]
    pub tab_label: String,
    /// The section heading it sits under, when it has one.
    #[serde(default)]
    pub group: String,
    #[serde(default)]
    pub label: String,
    /// The small print under the control, which often says what it is for in
    /// words closer to how somebody would ask for it than the label is.
    #[serde(default)]
    pub hint: String,
    /// What to look for once the right screen is showing: a `data-find` stamp,
    /// or `#id` for a control the page always has. Empty for a tab, which is
    /// its own destination.
    #[serde(default)]
    pub anchor: String,
    /// `field`, `button`, `tab` or `chrome`.
    #[serde(default)]
    pub kind: String,
}

impl Entry {
    /// Where this sits, for showing under the label: `Settlement / Land / Map`.
    pub fn path(&self) -> String {
        let parts = [&self.mode_label, &self.tab_label, &self.group];
        parts
            .iter()
            .filter(|p| !p.is_empty())
            .map(|p| p.as_str())
            .collect::<Vec<_>>()
            .join(" / ")
    }
}

/// One search. Everything but the query has a sensible nothing, so a caller
/// with no context can leave it out and still get the plain ranking.
#[derive(Clone, Copy, Debug)]
pub struct Search<'a> {
    pub query: &'a str,
    /// Fold in the offline meaning table as well as the letters typed.
    pub by_meaning: bool,
    /// The mode and tab showing right now. Matches there are nudged up: what
    /// somebody is looking at is the likeliest thing they mean.
    pub here: (&'a str, &'a str),
    pub limit: usize,
}

impl<'a> Search<'a> {
    pub fn new(query: &'a str) -> Search<'a> {
        Search { query, ..Search::default() }
    }

    pub fn from(mut self, mode: &'a str, tab: &'a str) -> Search<'a> {
        self.here = (mode, tab);
        self
    }
}

impl Default for Search<'_> {
    fn default() -> Self {
        Search { query: "", by_meaning: false, here: ("", ""), limit: DEFAULT_LIMIT }
    }
}

/// A scored entry. `idx` indexes `Index::entries` and survives sorting.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Hit {
    pub idx: usize,
    pub score: f64,
    /// Whether meaning matching, rather than the letters typed, is what put
    /// this here. The list marks those so a surprising result explains itself.
    pub by_meaning: bool,
}

/// What a query is matched against, and how much each part counts. The label
/// is what somebody is most likely to be typing; the hint is the loosest, so a
/// hint match alone should rank below a label match.
const W_LABEL: f64 = 1.0;
const W_GROUP: f64 = 0.55;
const W_TAB: f64 = 0.5;
const W_HINT: f64 = 0.42;

pub struct Index {
    pub entries: Vec<Entry>,
    /// Lowercased haystacks per entry, weighted, built once at load.
    hay: Vec<Vec<(String, f64)>>,
    /// Optional meaning table, keyed by the same entry order.
    terms: Option<Terms>,
}

/// The meaning table: a word to the entries it is close to, with a similarity
/// quantized into a byte. Built offline against an embedding model, because
/// the model is thirty megabytes and this runs in a page.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Terms {
    /// Identifies the index this was built against. A table built for a
    /// different set of entries points at the wrong things, so it is refused.
    #[serde(default)]
    pub stamp: String,
    #[serde(default)]
    pub words: HashMap<String, Vec<(u32, u8)>>,
}

impl Index {
    pub fn builtin() -> Index {
        let mut index = Index::new(serde_json::from_str(INDEX_JSON).unwrap_or_default());
        if let Ok(terms) = serde_json::from_str::<Terms>(TERMS_JSON) {
            index.set_terms(terms);
        }
        index
    }

    pub fn new(entries: Vec<Entry>) -> Index {
        let hay = entries
            .iter()
            .map(|e| {
                let mut v = vec![(e.label.to_lowercase(), W_LABEL)];
                for (text, weight) in [
                    (&e.group, W_GROUP),
                    (&e.tab_label, W_TAB),
                    (&e.hint, W_HINT),
                ] {
                    if !text.is_empty() {
                        v.push((text.to_lowercase(), weight));
                    }
                }
                v
            })
            .collect();
        Index { entries, hay, terms: None }
    }

    /// A stamp over the entries, so a meaning table can say which index it was
    /// built for. Order matters: the table points at entries by position.
    pub fn stamp(&self) -> String {
        // FNV-1a over what identifies each entry. Nothing here is a secret, it
        // only has to change when the menus do.
        let mut h: u64 = 0xcbf2_9ce4_8422_2325;
        for e in &self.entries {
            for part in [&e.mode, &e.tab, &e.label, &e.anchor] {
                for b in part.as_bytes() {
                    h ^= *b as u64;
                    h = h.wrapping_mul(0x100_0000_01b3);
                }
                h ^= 0xff;
                h = h.wrapping_mul(0x100_0000_01b3);
            }
        }
        format!("{h:016x}")
    }

    /// Takes a meaning table, if it was built for this index. Returns whether
    /// it was kept, so a toggle can say why it did nothing.
    pub fn set_terms(&mut self, terms: Terms) -> bool {
        if terms.stamp != self.stamp() {
            self.terms = None;
            return false;
        }
        self.terms = Some(terms);
        true
    }

    pub fn has_terms(&self) -> bool {
        self.terms.is_some()
    }

    /// Ranks the whole index, best first. An empty query yields every entry in
    /// index order, so the box with nothing typed in it is a browsable outline
    /// of the menus rather than a blank.
    ///
    /// `by_meaning` turns on the offline table; with no table loaded it is
    /// ignored and the ranking is the fuzzy one.
    pub fn search(&self, s: Search) -> Vec<Hit> {
        let words = query_words(s.query);
        if words.is_empty() {
            // With nothing typed there is nothing to rank, but there is still
            // somewhere to start: what is on the screen already.
            let mut order: Vec<usize> = (0..self.entries.len()).collect();
            order.sort_by(|a, b| {
                self.near(&self.entries[*b], s.here)
                    .total_cmp(&self.near(&self.entries[*a], s.here))
                    .then_with(|| a.cmp(b))
            });
            return order
                .into_iter()
                .take(s.limit)
                .map(|idx| Hit { idx, score: 0.0, by_meaning: false })
                .collect();
        }

        let meaning = match (s.by_meaning, &self.terms) {
            (true, Some(t)) => t.scores(&words, self.entries.len()),
            _ => Vec::new(),
        };

        let whole = words.join(" ");
        let mut hits: Vec<Hit> = Vec::new();
        for (idx, hay) in self.hay.iter().enumerate() {
            let fuzzy = score_entry(&words, &whole, hay);
            // Meaning is deliberately worth a shade less than letters, so
            // typing a label exactly never gets pushed down by a hunch.
            let sense = meaning.get(idx).copied().unwrap_or(0.0) * 0.9;
            let score = fuzzy.max(sense);
            if score < FLOOR {
                continue;
            }
            // The nudge is added after the floor, so being on this tab cannot
            // drag something in that was not worth showing at all.
            let score = score + self.near(&self.entries[idx], s.here);
            hits.push(Hit { idx, score, by_meaning: sense > fuzzy });
        }
        hits.sort_by(|a, b| {
            b.score
                .total_cmp(&a.score)
                .then_with(|| self.entries[a.idx].label.len().cmp(&self.entries[b.idx].label.len()))
                .then_with(|| a.idx.cmp(&b.idx))
        });
        hits.truncate(s.limit);
        hits
    }

    /// What this entry is worth for being where somebody already is. Chrome
    /// belongs to no mode and is equally near from everywhere, so it gets
    /// nothing rather than being pushed down from every screen.
    fn near(&self, entry: &Entry, here: (&str, &str)) -> f64 {
        let (mode, tab) = here;
        if entry.mode.is_empty() || entry.mode != mode {
            return 0.0;
        }
        if entry.tab == tab {
            NEAR_MODE + NEAR_TAB
        } else {
            NEAR_MODE
        }
    }
}

impl Terms {
    /// The meaning score per entry for a set of query words, in 0..1. A word
    /// the table has never seen contributes nothing rather than dragging the
    /// average down, or a query with one odd word in it would score nothing.
    fn scores(&self, words: &[String], entries: usize) -> Vec<f64> {
        let mut acc = vec![0.0; entries];
        let mut seen = 0;
        for w in words {
            let list = match self.words.get(w) {
                Some(l) => l,
                None => continue,
            };
            seen += 1;
            for (idx, s) in list {
                if let Some(slot) = acc.get_mut(*idx as usize) {
                    *slot += *s as f64 / 255.0;
                }
            }
        }
        if seen == 0 {
            return Vec::new();
        }
        for a in acc.iter_mut() {
            *a = (*a / seen as f64).min(1.0);
        }
        acc
    }
}

/// Splits a query into lowercase words. Punctuation is separator, so `cell-px`
/// and `cell px` ask the same thing.
pub fn query_words(query: &str) -> Vec<String> {
    query
        .split(|c: char| !c.is_alphanumeric())
        .filter(|w| !w.is_empty())
        .map(|w| w.to_lowercase())
        .collect()
}

/// Every query word has to land somewhere on this entry, or the entry is out.
/// Typing a second word should narrow the list rather than widen it.
fn score_entry(words: &[String], whole: &str, hay: &[(String, f64)]) -> f64 {
    let mut total = 0.0;
    for w in words {
        let mut best: f64 = 0.0;
        for (text, weight) in hay {
            best = best.max(weight * word_score(w, text));
        }
        if best <= 0.0 {
            return 0.0;
        }
        total += best;
    }
    let mut score = total / words.len() as f64;
    // Typing the start of a label should put that label first, however many
    // other things happen to contain the same letters.
    if let Some((label, _)) = hay.first() {
        if label.starts_with(whole) {
            score = score.max(0.99);
        }
        // Longer labels have more room to match by accident.
        score -= label.len() as f64 * 1e-4;
    }
    score
}

/// How well one query word matches one haystack, in 0..1.
fn word_score(needle: &str, hay: &str) -> f64 {
    if hay == needle {
        return 1.0;
    }
    let mut best: f64 = 0.0;
    for word in hay.split(|c: char| !c.is_alphanumeric()) {
        if word.is_empty() {
            continue;
        }
        if word == needle {
            return 0.95;
        }
        if word.starts_with(needle) {
            best = best.max(0.6 + 0.3 * (needle.len() as f64 / word.len() as f64));
        }
    }
    if best > 0.0 {
        return best;
    }
    if hay.contains(needle) {
        return 0.58;
    }
    subsequence(needle, hay)
}

/// The letters of `needle` in order somewhere in `hay`, scored by how close
/// together they landed: `clpx` is a good stab at `cell px` and a poor one at
/// `colonists leave when prices xxx`.
fn subsequence(needle: &str, hay: &str) -> f64 {
    let hay: Vec<char> = hay.chars().collect();
    let mut at = 0usize;
    let mut first: Option<usize> = None;
    let mut last = 0usize;
    for ch in needle.chars() {
        let hit = hay.iter().skip(at).position(|h| *h == ch).map(|i| i + at);
        match hit {
            Some(i) => {
                first.get_or_insert(i);
                last = i;
                at = i + 1;
            }
            None => return 0.0,
        }
    }
    let first = match first {
        Some(f) => f,
        None => return 0.0,
    };
    let span = (last - first + 1) as f64;
    0.5 * (needle.chars().count() as f64 / span)
}
